# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

campaignchain_activity_gotowebinar_new:
    pattern:  /activity/gotowebinar/new
    defaults: { _controller: campaignchain.activity.controller.gotowebinar.add:newAction }

campaignchain_activity_gotowebinar_edit:
    pattern:  /activity/gotowebinar/{id}/edit
    defaults: { _controller: campaignchain.activity.controller.gotowebinar.add:readAction }

campaignchain_activity_gotowebinar_edit_modal:
    pattern:  /modal/activity/gotowebinar/{id}/edit
    defaults: { _controller: campaignchain.activity.controller.gotowebinar.add:editModalAction }

campaignchain_activity_gotowebinar_read:
    pattern:  /activity/gotowebinar/{id}
    defaults: { _controller: campaignchain.activity.controller.gotowebinar.add:readAction }