# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

campaignchain_activity_gotowebinar_new:
    pattern:  /activity/gotowebinar/new
    defaults: { _controller: CampaignChainActivityGoToWebinarBundle:Default:new }

campaignchain_activity_gotowebinar_edit:
    pattern:  /activity/gotowebinar/{id}/edit
    defaults: { _controller: CampaignChainActivityGoToWebinarBundle:Default:edit }

campaignchain_activity_gotowebinar_edit_modal:
    pattern:  /modal/activity/gotowebinar/{id}/edit
    defaults: { _controller: CampaignChainActivityGoToWebinarBundle:Default:editModal }

campaignchain_activity_gotowebinar_read:
    pattern:  /activity/gotowebinar/{id}
    defaults: { _controller: CampaignChainActivityGoToWebinarBundle:Default:read }